language: node_js
node_js:
- 8.9.0
cache:
  directories:
  - node_modules
before_install:
- npm install hexo-cli -g
install:
- yarn
script:
- hexo clean
- hexo generate
- hexo g
- hexo d
after_success:
  - cd ./public
  - git init
  - git config user.name "christian"
  - git config user.email "baozaodexianyu@163.com"
  - git add .
  - git commit -m "TravisCI 自动部署"
  # Github Pages
  - git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" master:master 
  # Coding Pages
  # - git push --force --quiet "https://coding用户名:${CO_TOKEN}@${CO_REF}" master:master
  - git push https://git.dev.tencent.com/chriskowk/kowk_blog.git --all
branches:
  only:
  - dev

env:
 global:
   # Github Pages
   - GH_REF: https://github.com/rollawaypoint/rollawaypoint.github.io
   # Coding Pages
   - CO_REF: https://git.dev.tencent.com/chriskowk/kowk_blog.git