name: Publish GitHub Pages

on:
  push:
    branches:
      - v6

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0

      - name: Install dependencies
        run: yarn

      - name: Build the project
        run: yarn build

      - name: Check public directory
        run: ls -l ./public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: false
          force_orphan: true
